apiVersion: skaffold/v2beta5
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: latest
  artifacts:
    - image: tnexus/sample-ctx-jib
      jib:
        project: com.example:demo
        args:
          - -Pskaffold_profile
          - -Djib_property
deploy:
  kubectl:
    manifests:
      - k8s/*.yml
