apiVersion: skaffold/v2beta5
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: latest
  artifacts:
  - image: tnexus/sample-ctx-jib
    jib:
      project: com.example:demo
      args:
      - -Pskaffold_profile
      - -Djib_property
    platforms:
    - linux/amd64 # Specify the desired platform here
deploy:
  kubectl:
    manifests:
    - k8s/*.yml
