apiVersion: v1
kind: Service
metadata:
  name: sample-ctx-context-service-external
  labels:
    name: sample-ctx-context-service-external
spec:
  type: NodePort
  ports:
    - port: 8282
      targetPort: 8282
      nodePort: 30182
  selector:
    app: sample-ctx-context
