apiVersion: v1
kind: Service
metadata:
  name: sample-ctx-context-service-internal # this is the host of service
  labels:
    name: sample-ctx-context-service-internal
spec:
  ports:
    - port: 8282 # this is the port of internal service
      targetPort: 8282
  selector:
    app: sample-ctx-context